name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build collection and deploy to Galaxy
        run: |
          ls -l
          #VERSION=`grep "version: " galaxy.yml | awk {'print $2'}`
          #ansible-galaxy collection build
          #ansible-galaxy collection publish -s https://galaxy.ansible.com/api --token ${{ secrets.GALAXY }} hikari661-argostranslate-$VERSION.tar.gz
        #working-directory: hikari661/translate

